#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_ESC, RALT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G, KC_H, LGUI_T(KC_J), LALT_T(KC_K), LCTL_T(KC_L), RALT_T(KC_SCLN), KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LALT, KC_NO, KC_NO, KC_RCTL, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LCTL, KC_LGUI, MO(1), KC_BSPC, KC_DEL, KC_ENT, KC_SPC, MO(2), KC_RALT, KC_LCTL),

[_LAYER1] = LAYOUT(KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO, KC_ESC, RALT_T(KC_1), LCTL_T(KC_2), LALT_T(KC_3), LGUI_T(KC_4), KC_5, KC_6, LGUI_T(KC_7), LALT_T(KC_8), LCTL_T(KC_9), RALT_T(KC_0), KC_MINS, KC_LSFT, KC_NO, KC_EQL, KC_PIPE, KC_QUES, KC_NO, KC_LALT, KC_NO, KC_NO, KC_RCTL, KC_NO, KC_GRV, KC_TILD, KC_RBRC, KC_RCBR, KC_RSFT, KC_LCTL, KC_LGUI, KC_TRNS, KC_BSPC, KC_DEL, KC_ENT, KC_SPC, KC_TRNS, KC_RALT, KC_LCTL),

[_LAYER2] = LAYOUT(KC_TAB, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_ESC, RALT_T(KC_F11), LCTL_T(KC_F12), LALT_T(KC_NO), LGUI_T(KC_NO), KC_PSCR, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_CAPS, KC_LALT, KC_NO, KC_NO, KC_RCTL, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_RSFT, KC_LCTL, KC_LGUI, KC_TRNS, KC_BSPC, KC_DEL, KC_ENT, KC_SPC, KC_TRNS, KC_RALT, KC_LCTL)

};
